# Generated by Xplorer, do not modify.
# This Makefile builds _single_build Debug

%:: RCS/%,v
%:: RCS/%
%:: s.%
%:: SCCS/s.%
.SUFFIXES:
.SUFFIXES: .a .o .c .cc .C .cpp .s .S .h

all:
	/bin/sh -c " cd /devHData/DSP_work/xtensa/xtensa/Xplorer-solo-10.1.11-linux-x64-installer.bin/Xplorer-10.1.11-workspaces/workspace/jili/bin/visionp6_ao/Debug && $(MAKE) all  "

clean:
	/bin/sh -c " cd /devHData/DSP_work/xtensa/xtensa/Xplorer-solo-10.1.11-linux-x64-installer.bin/Xplorer-10.1.11-workspaces/workspace/jili/bin/visionp6_ao/Debug && $(MAKE) clean  "
